.PHONY: all
all: FusionBridge FusionCore DataSorcerers

.PHONY: clean
clean:
	make -C FusionBridge clean
	make -C FusionCore clean
	make -C DataSorcerers clean

.PHONY: FusionBridge
FusionBridge:
	make -C FusionBridge

.PHONY: FusionCore
FusionCore:
	make -C FusionCore

.PHONY: DataSorcerers
DataSorcerers:
	make -C DataSorcerers
